# Branch Protection Rules Configuration
# Note: This file documents the recommended settings.
# Apply these via GitHub Settings > Branches or using GitHub CLI/API

main:
  protection_rules:
    # Require PR before merging
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      require_last_push_approval: false
      
    # Status checks
    required_status_checks:
      strict: true  # Require branches to be up to date
      contexts:
        - "test (18.x)"
        - "test (20.x)"
        - "test (22.x)"
        - "changesets"
    
    # Branch restrictions
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: false
    
    # Merge settings
    allow_merge_commits: true
    allow_squash_merge: true
    allow_rebase_merge: true
    allow_auto_merge: true
    delete_branch_on_merge: true
    
    # Conversation resolution
    required_conversation_resolution: true
    
develop:
  protection_rules:
    required_pull_request_reviews:
      required_approving_review_count: 0  # Optional reviews for develop
      dismiss_stale_reviews: true
      
    required_status_checks:
      strict: false
      contexts:
        - "test (20.x)"  # Only test on Node 20 for develop
    
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false