export const HTTP_MODULE_OPTIONS = Symbol('HTTP_MODULE_OPTIONS');
export const HTTP_MODULE_ID = Symbol('HTTP_MODULE_ID');

export const HTTP_DEFAULTS = {
  CONNECTION_COUNT: 10,
  PIPELINING_LIMIT: 10,
  KEEP_ALIVE_TIMEOUT: 4000,
  KEEP_ALIVE_MAX_TIMEOUT: 600000,
  CONNECT_TIMEOUT: 10000,
  BODY_TIMEOUT: 30000,
  HEADERS_TIMEOUT: 30000,
  DEFAULT_METHOD: 'GET',
  DEFAULT_RESPONSE_TYPE: 'json',
  DEFAULT_CONTENT_TYPE: 'application/json',
  OK_STATUS: 200,
  OK_STATUS_TEXT: 'OK',
  ERROR_STATUS_TEXT: 'Error',
} as const;